# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-26 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='shortdescription',
            new_name='short_description',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='timecreated',
            new_name='time_created',
        ),
    ]
